services:
  image-trainer:
    deploy:
      # resources:
      #   limits:
      #     memory: 24G
      #   reservations:
      #     devices:
      #       - driver: nvidia
      #         device_ids: [all]
      #         capabilities: [gpu]
    shm_size: "8gb"
    network_mode: host
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile

    env_file:
      - d.env
    # command:
    #   [
    #     "python",
    #     "/home/user/YOLO/YOLO/download_script.py",
    #     "crlab",
    #     "redi/",
    #   ]
    volumes:
      - ./app:/home/user/ImageTrainer/app
    command: ["./app/startup_script.sh"]
